### ISSUE TITLE
小冰内置文字游戏物品名称征集

### ISSUE THREAD

**Issue by HereIsYui** [HereIsYui/pwl-xiaoice#5]
一个人想的头都大了，大家一起出出主意吧![图片表情](https://gsp0.baidu.com/5aAHeD3nKhI2p27j8IqW0jdnxx1xbK/tb/editor/images/client/image_emoticon95.png)

现需征集一下物品名称要名字就行

* 场景名称
* 魔兽名称
* 材料名称
* 丹药名称
* 武器名称
* 防具名称

没有数量上限，越多越好，我会都加入到游戏中哦~

**Comment by chenyi729** [comment]
飞来峰

**Comment by chenyi729** [comment]
魔兽的话可以参考山海经

**Comment by chenyi729** [comment]
蛊雕   旋龟   梼杌拼音táowù    毕方   白泽

**Comment by chenyi729** [comment]
鲲鹏，独角兽，混沌，飞廉，夔kuí牛，鬼车，重明鸟，当康，英招，化蛇，祸斗，蚣蝮，猰貐，虚耗，貔貅，负屃，螭吻，霸下，狴犴，蒲牢，狻猊，蜚，青龙，白虎，朱雀，玄武，当康，嘲风，睚毗，囚牛，蟠龙，蛟龙，螭龙，应龙，肥遗，白矖，麒麟，白泽，陵鱼，梼杌，穷奇，烛龙，精卫，狸力，举父，帝江，蛊雕，獓狠，饕餮，䑏（huān）疏，九尾狐，吼，狰章峨山，讙，钟山神，巴蛇，夸父，旋龟，灌灌，赤鱬，长右，猾褢，猼訑，瞿如，虎蛟，凤凰，虫遗，肥遗，狌狌，鹿蜀，女娲，豪彘，羬羊，鹦鹉，数斯，鸾鸟，胜遇，毕方，天狗，鵸鵌，蠃鱼，鯥，类，颙，玃，西王母，狰，狡，冉遗鱼，驳，乘黄，讹兽，风生兽，夫诸，姑获鸟，鲛人，英招，傒囊，狸力，猫将军，雨师妾，彘，猰貐，睚毗，猲狙，虚耗，挟翼，相柳，文鳐鱼，溪边，魍魉，土蝼，兕，天吴，竦斯，酸与，狻猊，双双，胜遇，尚付，山臊，山膏，三足乌，三足龟，蓐收，青鸟，钦原，钦丕，鵸余，蒲牢，狍鸮，鸣蛇，孟极，灭蒙鸟，蛮蛮，马腹，鸰，祸斗，火鼠，患，何罗鱼，横公鱼，獬豸，狴犴，赤鱬，天狐，辟邪，刑天，雷神，屏蓬，火光兽，陵鱼，猰貐，角端，诸怀，乘黄，夫诸，朱厌，天马，九婴，钩蛇，凿齿，祸斗，陆吾，当扈，赤眼猪妖，比翼鸟，应龙，英招，鱼妇，九凤，化蛇，相柳氏，犀渠，何罗鱼，耳鼠，罴，橐驼，犀，驺虞，孰湖。

**Comment by HereIsYui** [comment]
> 鲲，独角兽，混浊当康飞廉，夔kuí牛，鬼车，重明鸟，，英招，化，祸斗，蚣蝮，猰貐，蛇耗，貔貅，屃，螭吻，下，狴犴，蒲牢，狻猊，蜚，青龙，白虎，朱雀，玄武，当康，雅风霸，睚毗，囚牛，龙，蛟龙，螭龙，应龙，肥遗白矖，麒麟，白泽，陵鱼，梼杌，穷奇，烛龙，精卫，狸力，举父，帝江，蛊雕，獓狠，饕餮，䑏（huān）疏，九尾狐，吼，狰章峨山，讙，山神，巴蛇，夸父，龟旋，灌灌，赤鱬，长右，位置褢，猼訑，瞿如，虎蛟，凤凰，虫遗，肥遗，狌狌，鹿蜀，女娲，豪彘，羬羊，鹦鹉，数斯，鸾鸟，胜遇，毕方，天狗，鵸鵌，蠃鱼，鯥，类，颙，玃，西王母，狰，狡猾，冉遗鱼，辩，乘黄，诈兽，风生兽，夫诸，姑获鸟，鲛人，英招，傒囊，狸力，猫将军，师雨妃，彘，猰貐，睚毗，猲狙，虚耗，挟翼，相柳，文鳐鱼，溪边，魍魉，土蝼，兕，天吴，竦斯，酸与，狻猊，双双，胜遇，尚付，山臊，山膏，三足乌，三足龟，蓐收，青鸟，钦原，钦丕，鵸余，蒲牢，狍鸮，鸣蛇，孟极，灭蒙鸟，蛮蛮，马腹，鸰，祸斗，火鼠，患，何罗鱼，横公鱼，獬豸，狴犴，赤鱬，天狐，治病，刑天，雷神，屏蓬，火光兽，陵鱼，猰貐，角端，怀，乘黄，夫诸，朱厌，天马，九婴，钩蛇，凿齿，祸斗，陆吾，当扈，赤眼猪妖，比翼鸟，应龙，英招，鱼妇，九凤，化蛇，相柳氏，犀犀渠，何罗鱼，鼠，罴，橐麋，犀，驺，两湖。

太强了太强了感谢大佬

**Comment by iwpz** [comment]
场景名称：办公室
魔兽名称：摸鱼兽
丹药名称：划水丹
武器名称：偷懒键盘
防具名称：美梦盾
